### ISSUE TITLE
Using the nightly build version of typescript is dangerous

### ISSUE THREAD

**Issue by scharf** [barbatus/meteor-typescript#3]
When using meteor-typesctipt in a production environment it is dangerous to use ["typescript": "next"](https://github.com/barbatus/meteor-typescript/blob/f6153cac0d808de89e10bf24468893dde0f82e97/package.json#L31) which is the [nightly build version](https://www.npmjs.com/package/typescript) of typescript.

I got version `1.9.0-dev.20160412` of typescript which causes all kinds of problems.

Is there a way to install a stable version of typescript with npm that meteor-typescript then uses?

**Comment by barbatus** [comment]
What problems do you have specifically?
I have bunch of tests and they run ok.

**Comment by csillag** [comment]
It's not a question of what exactly fails today. 

The problem is the package (as it is configured today) introduces unpredictable behavior, since it depends on the latest nightly build, which might change or break at any time.

How about making "typescript" into a peer dependency, so that this decision can be made by the app developer instead?

**Comment by scharf** [comment]
Thx -- we switched to a setup where we transpile the typescript outside the meteor build process -- this gives us control over the version we are using.
