### ISSUE TITLE
Upgrade to typescript 2.1

### ISSUE THREAD

**Issue by scharf** [barbatus/meteor-typescript#4]
Typescript 2.1 is out -- it would be nice to be able to use this version.

In general, it seems quite complicated to upgrade to new versions of typescript. Is there a way to tell this plugin to use a typescript version that is installed outside of meteor (via npm)?

**Comment by barbatus** [comment]
It's not complicated. It needs typescript version update in this package, checking if tests are good, and then publishing a new version.
While it's likely possible to use typescript from the app itself, there will be own issues with that for sure, one of them is that due to size of the typescript it takes quit a while to build the typescript compiler package (which one will face each time rebuilding his app).
So now typescript is used indirectly in the compiler package (https://github.com/barbatus/typescript-compiler/blob/master/package.js#L10), in the same way as Babel-compiler package https://github.com/meteor/meteor/tree/devel/packages/babel-compiler.

I updated typescript to 2.0.10 so run meteor update; there is an issue prevents updating to 2.1.1 that I am checking now (https://github.com/Microsoft/TypeScript/issues/12397)

**Comment by barbatus** [comment]
Upgraded, https://github.com/barbatus/typescript/releases
